services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "7"
      RAM_SIZE: "12G"
      CPU_CORES: "8"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    stop_grace_period: 60m
